#!/bin/sh

if [ "$LEFTHOOK_VERBOSE" = "1" ] || [ "$LEFTHOOK_VERBOSE" = "true" ]; then
  set -x
fi

if [ "$LEFTHOOK" = "0" ]; then
  exit 0
fi

if [ -n "$LEFTHOOK_BIN" ]; then
  "$LEFTHOOK_BIN" run "pre-commit" "$@"
  exit $?
fi

if lefthook -h >/dev/null 2>&1; then
  lefthook run "pre-commit" "$@"
  exit $?
fi

dir="$(git rev-parse --show-toplevel)"
os_arch=$(uname | tr '[:upper:]' '[:lower:]')
cpu_arch=$(uname -m | sed 's/aarch64/arm64/;s/x86_64/x64/')

if [ -f "$dir/node_modules/lefthook-${os_arch}-${cpu_arch}/bin/lefthook" ]; then
  "$dir/node_modules/lefthook-${os_arch}-${cpu_arch}/bin/lefthook" run "pre-commit" "$@"
elif [ -f "$dir/node_modules/@evilmartians/lefthook/bin/lefthook-${os_arch}-${cpu_arch}/lefthook" ]; then
  "$dir/node_modules/@evilmartians/lefthook/bin/lefthook-${os_arch}-${cpu_arch}/lefthook" run "pre-commit" "$@"
elif [ -f "$dir/node_modules/@evilmartians/lefthook-installer/bin/lefthook" ]; then
  "$dir/node_modules/@evilmartians/lefthook-installer/bin/lefthook" run "pre-commit" "$@"
elif [ -f "$dir/node_modules/lefthook/bin/index.js" ]; then
  "$dir/node_modules/lefthook/bin/index.js" run "pre-commit" "$@"
elif go tool lefthook -h >/dev/null 2>&1; then
  go tool lefthook run "pre-commit" "$@"
elif bundle exec lefthook -h >/dev/null 2>&1; then
  bundle exec lefthook run "pre-commit" "$@"
elif yarn lefthook -h >/dev/null 2>&1; then
  yarn lefthook run "pre-commit" "$@"
elif pnpm lefthook -h >/dev/null 2>&1; then
  pnpm lefthook run "pre-commit" "$@"
elif swift package lefthook >/dev/null 2>&1; then
  swift package --build-path .build/lefthook --disable-sandbox lefthook run "pre-commit" "$@"
elif command -v mint >/dev/null 2>&1; then
  mint run csjones/lefthook-plugin run "pre-commit" "$@"
elif uv run lefthook -h >/dev/null 2>&1; then
  uv run lefthook run "pre-commit" "$@"
elif mise exec -- lefthook -h >/dev/null 2>&1; then
  mise exec -- lefthook run "pre-commit" "$@"
elif devbox run lefthook -h >/dev/null 2>&1; then
  devbox run lefthook run "pre-commit" "$@"
else
  echo "Can't find lefthook in PATH"
fi
